// Creates a PR and comments on the linked issue.
// Expects env: BRANCH, ISSUE_NUMBER, ISSUE_TITLE

module.exports = async ({ github, context, core }) => {
  const fs = require('fs');
  let summary = '';
  try {
    summary = fs.readFileSync('/tmp/pi-summary.md', 'utf-8');
  } catch {
    summary = '(no summary generated)';
  }

  const issueNumber = parseInt(process.env.ISSUE_NUMBER);
  const body = `Closes #${issueNumber}\n\n`
    + `${summary}\n\n`
    + `---\n_Generated by [pi coding agent](https://github.com/badlogic/pi-mono)_`;

  const pr = await github.rest.pulls.create({
    owner: context.repo.owner,
    repo: context.repo.repo,
    title: `[pi-agent] ${process.env.ISSUE_TITLE}`,
    body,
    head: process.env.BRANCH,
    base: 'main',
  });

  await github.rest.issues.createComment({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: issueNumber,
    body: `🤖 Pi agent has created PR #${pr.data.number} to address this issue.`,
  });
};
